name: Send Weekly PR Report

on:
  schedule:
    - cron: '0 9 * * MON' # Runs every Monday at 9:00 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  send_pr_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install axios

    - name: Save fetch PRs script
      run: |
        cat << 'EOF' > fetch_prs.js
        const axios = require('axios');
        const fs = require('fs');
        const oneWeekAgo = new Date();
        oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
        const since = oneWeekAgo.toISOString();
        const repo = process.env.GITHUB_REPOSITORY;
        const token = process.env.GITHUB_TOKEN;

        console.log('Fetching pull requests from repository:', repo);
        console.log('Since date:', since);

        axios.get(`https://api.github.com/repos/${repo}/pulls?state=all&since=${since}`, {
          headers: {
            Authorization: `token ${token}`
          }
        })
        .then(response => {
          const prs = response.data;
          const prList = prs.map(pr => `#${pr.number} - ${pr.title} by ${pr.user.login}`).join('\n');
          console.log('Formatted pull request list:', prList);
          fs.writeFileSync('pr_list.txt', prList);
        })
        .catch(error => {
          console.error('Error fetching pull requests:', error);
          process.exit(1);
        });
        EOF

    - name: Fetch pull requests from the last week
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node fetch_prs.js

    - name: Send email with PR list
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: 'smtp.gmail.com'
        server_port: 587
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: 'Weekly Pull Request Report'
        body: |
          Here are the pull requests from the last week:

          ${{ steps.fetch_prs.outputs.pr_list }}
        to: 'chaopan@microsoft.com'
        from: 'chaopanultra@gmail.com'
        content_type: 'text/plain'
